// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/calculators/util/landmarks_to_render_data_calculator.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mediapipe_2fcalculators_2futil_2flandmarks_5fto_5frender_5fdata_5fcalculator_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mediapipe_2fcalculators_2futil_2flandmarks_5fto_5frender_5fdata_5fcalculator_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "mediapipe/framework/calculator.pb.h"
#include "mediapipe/util/color.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mediapipe_2fcalculators_2futil_2flandmarks_5fto_5frender_5fdata_5fcalculator_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mediapipe_2fcalculators_2futil_2flandmarks_5fto_5frender_5fdata_5fcalculator_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mediapipe_2fcalculators_2futil_2flandmarks_5fto_5frender_5fdata_5fcalculator_2eproto;
namespace mediapipe {
class LandmarksToRenderDataCalculatorOptions;
struct LandmarksToRenderDataCalculatorOptionsDefaultTypeInternal;
extern LandmarksToRenderDataCalculatorOptionsDefaultTypeInternal _LandmarksToRenderDataCalculatorOptions_default_instance_;
}  // namespace mediapipe
PROTOBUF_NAMESPACE_OPEN
template<> ::mediapipe::LandmarksToRenderDataCalculatorOptions* Arena::CreateMaybeMessage<::mediapipe::LandmarksToRenderDataCalculatorOptions>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mediapipe {

// ===================================================================

class LandmarksToRenderDataCalculatorOptions final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mediapipe.LandmarksToRenderDataCalculatorOptions) */ {
 public:
  inline LandmarksToRenderDataCalculatorOptions() : LandmarksToRenderDataCalculatorOptions(nullptr) {}
  ~LandmarksToRenderDataCalculatorOptions() override;
  explicit constexpr LandmarksToRenderDataCalculatorOptions(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  LandmarksToRenderDataCalculatorOptions(const LandmarksToRenderDataCalculatorOptions& from);
  LandmarksToRenderDataCalculatorOptions(LandmarksToRenderDataCalculatorOptions&& from) noexcept
    : LandmarksToRenderDataCalculatorOptions() {
    *this = ::std::move(from);
  }

  inline LandmarksToRenderDataCalculatorOptions& operator=(const LandmarksToRenderDataCalculatorOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline LandmarksToRenderDataCalculatorOptions& operator=(LandmarksToRenderDataCalculatorOptions&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LandmarksToRenderDataCalculatorOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const LandmarksToRenderDataCalculatorOptions* internal_default_instance() {
    return reinterpret_cast<const LandmarksToRenderDataCalculatorOptions*>(
               &_LandmarksToRenderDataCalculatorOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(LandmarksToRenderDataCalculatorOptions& a, LandmarksToRenderDataCalculatorOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(LandmarksToRenderDataCalculatorOptions* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LandmarksToRenderDataCalculatorOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LandmarksToRenderDataCalculatorOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<LandmarksToRenderDataCalculatorOptions>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const LandmarksToRenderDataCalculatorOptions& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const LandmarksToRenderDataCalculatorOptions& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LandmarksToRenderDataCalculatorOptions* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mediapipe.LandmarksToRenderDataCalculatorOptions";
  }
  protected:
  explicit LandmarksToRenderDataCalculatorOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLandmarkConnectionsFieldNumber = 1,
    kLandmarkColorFieldNumber = 2,
    kConnectionColorFieldNumber = 3,
    kMinDepthLineColorFieldNumber = 12,
    kMaxDepthLineColorFieldNumber = 13,
    kVisibilityThresholdFieldNumber = 7,
    kPresenceThresholdFieldNumber = 9,
    kMinDepthCircleThicknessFieldNumber = 10,
    kUtilizeVisibilityFieldNumber = 6,
    kUtilizePresenceFieldNumber = 8,
    kVisualizeLandmarkDepthFieldNumber = 5,
    kThicknessFieldNumber = 4,
    kMaxDepthCircleThicknessFieldNumber = 11,
  };
  // repeated int32 landmark_connections = 1;
  int landmark_connections_size() const;
  private:
  int _internal_landmark_connections_size() const;
  public:
  void clear_landmark_connections();
  private:
  int32_t _internal_landmark_connections(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_landmark_connections() const;
  void _internal_add_landmark_connections(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_landmark_connections();
  public:
  int32_t landmark_connections(int index) const;
  void set_landmark_connections(int index, int32_t value);
  void add_landmark_connections(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      landmark_connections() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_landmark_connections();

  // optional .mediapipe.Color landmark_color = 2;
  bool has_landmark_color() const;
  private:
  bool _internal_has_landmark_color() const;
  public:
  void clear_landmark_color();
  const ::mediapipe::Color& landmark_color() const;
  PROTOBUF_NODISCARD ::mediapipe::Color* release_landmark_color();
  ::mediapipe::Color* mutable_landmark_color();
  void set_allocated_landmark_color(::mediapipe::Color* landmark_color);
  private:
  const ::mediapipe::Color& _internal_landmark_color() const;
  ::mediapipe::Color* _internal_mutable_landmark_color();
  public:
  void unsafe_arena_set_allocated_landmark_color(
      ::mediapipe::Color* landmark_color);
  ::mediapipe::Color* unsafe_arena_release_landmark_color();

  // optional .mediapipe.Color connection_color = 3;
  bool has_connection_color() const;
  private:
  bool _internal_has_connection_color() const;
  public:
  void clear_connection_color();
  const ::mediapipe::Color& connection_color() const;
  PROTOBUF_NODISCARD ::mediapipe::Color* release_connection_color();
  ::mediapipe::Color* mutable_connection_color();
  void set_allocated_connection_color(::mediapipe::Color* connection_color);
  private:
  const ::mediapipe::Color& _internal_connection_color() const;
  ::mediapipe::Color* _internal_mutable_connection_color();
  public:
  void unsafe_arena_set_allocated_connection_color(
      ::mediapipe::Color* connection_color);
  ::mediapipe::Color* unsafe_arena_release_connection_color();

  // optional .mediapipe.Color min_depth_line_color = 12;
  bool has_min_depth_line_color() const;
  private:
  bool _internal_has_min_depth_line_color() const;
  public:
  void clear_min_depth_line_color();
  const ::mediapipe::Color& min_depth_line_color() const;
  PROTOBUF_NODISCARD ::mediapipe::Color* release_min_depth_line_color();
  ::mediapipe::Color* mutable_min_depth_line_color();
  void set_allocated_min_depth_line_color(::mediapipe::Color* min_depth_line_color);
  private:
  const ::mediapipe::Color& _internal_min_depth_line_color() const;
  ::mediapipe::Color* _internal_mutable_min_depth_line_color();
  public:
  void unsafe_arena_set_allocated_min_depth_line_color(
      ::mediapipe::Color* min_depth_line_color);
  ::mediapipe::Color* unsafe_arena_release_min_depth_line_color();

  // optional .mediapipe.Color max_depth_line_color = 13;
  bool has_max_depth_line_color() const;
  private:
  bool _internal_has_max_depth_line_color() const;
  public:
  void clear_max_depth_line_color();
  const ::mediapipe::Color& max_depth_line_color() const;
  PROTOBUF_NODISCARD ::mediapipe::Color* release_max_depth_line_color();
  ::mediapipe::Color* mutable_max_depth_line_color();
  void set_allocated_max_depth_line_color(::mediapipe::Color* max_depth_line_color);
  private:
  const ::mediapipe::Color& _internal_max_depth_line_color() const;
  ::mediapipe::Color* _internal_mutable_max_depth_line_color();
  public:
  void unsafe_arena_set_allocated_max_depth_line_color(
      ::mediapipe::Color* max_depth_line_color);
  ::mediapipe::Color* unsafe_arena_release_max_depth_line_color();

  // optional double visibility_threshold = 7 [default = 0];
  bool has_visibility_threshold() const;
  private:
  bool _internal_has_visibility_threshold() const;
  public:
  void clear_visibility_threshold();
  double visibility_threshold() const;
  void set_visibility_threshold(double value);
  private:
  double _internal_visibility_threshold() const;
  void _internal_set_visibility_threshold(double value);
  public:

  // optional double presence_threshold = 9 [default = 0];
  bool has_presence_threshold() const;
  private:
  bool _internal_has_presence_threshold() const;
  public:
  void clear_presence_threshold();
  double presence_threshold() const;
  void set_presence_threshold(double value);
  private:
  double _internal_presence_threshold() const;
  void _internal_set_presence_threshold(double value);
  public:

  // optional double min_depth_circle_thickness = 10 [default = 0];
  bool has_min_depth_circle_thickness() const;
  private:
  bool _internal_has_min_depth_circle_thickness() const;
  public:
  void clear_min_depth_circle_thickness();
  double min_depth_circle_thickness() const;
  void set_min_depth_circle_thickness(double value);
  private:
  double _internal_min_depth_circle_thickness() const;
  void _internal_set_min_depth_circle_thickness(double value);
  public:

  // optional bool utilize_visibility = 6 [default = false];
  bool has_utilize_visibility() const;
  private:
  bool _internal_has_utilize_visibility() const;
  public:
  void clear_utilize_visibility();
  bool utilize_visibility() const;
  void set_utilize_visibility(bool value);
  private:
  bool _internal_utilize_visibility() const;
  void _internal_set_utilize_visibility(bool value);
  public:

  // optional bool utilize_presence = 8 [default = false];
  bool has_utilize_presence() const;
  private:
  bool _internal_has_utilize_presence() const;
  public:
  void clear_utilize_presence();
  bool utilize_presence() const;
  void set_utilize_presence(bool value);
  private:
  bool _internal_utilize_presence() const;
  void _internal_set_utilize_presence(bool value);
  public:

  // optional bool visualize_landmark_depth = 5 [default = true];
  bool has_visualize_landmark_depth() const;
  private:
  bool _internal_has_visualize_landmark_depth() const;
  public:
  void clear_visualize_landmark_depth();
  bool visualize_landmark_depth() const;
  void set_visualize_landmark_depth(bool value);
  private:
  bool _internal_visualize_landmark_depth() const;
  void _internal_set_visualize_landmark_depth(bool value);
  public:

  // optional double thickness = 4 [default = 1];
  bool has_thickness() const;
  private:
  bool _internal_has_thickness() const;
  public:
  void clear_thickness();
  double thickness() const;
  void set_thickness(double value);
  private:
  double _internal_thickness() const;
  void _internal_set_thickness(double value);
  public:

  // optional double max_depth_circle_thickness = 11 [default = 18];
  bool has_max_depth_circle_thickness() const;
  private:
  bool _internal_has_max_depth_circle_thickness() const;
  public:
  void clear_max_depth_circle_thickness();
  double max_depth_circle_thickness() const;
  void set_max_depth_circle_thickness(double value);
  private:
  double _internal_max_depth_circle_thickness() const;
  void _internal_set_max_depth_circle_thickness(double value);
  public:

  static const int kExtFieldNumber = 258435389;
  static ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::mediapipe::CalculatorOptions,
      ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::mediapipe::LandmarksToRenderDataCalculatorOptions >, 11, false >
    ext;
  // @@protoc_insertion_point(class_scope:mediapipe.LandmarksToRenderDataCalculatorOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > landmark_connections_;
  ::mediapipe::Color* landmark_color_;
  ::mediapipe::Color* connection_color_;
  ::mediapipe::Color* min_depth_line_color_;
  ::mediapipe::Color* max_depth_line_color_;
  double visibility_threshold_;
  double presence_threshold_;
  double min_depth_circle_thickness_;
  bool utilize_visibility_;
  bool utilize_presence_;
  bool visualize_landmark_depth_;
  double thickness_;
  double max_depth_circle_thickness_;
  friend struct ::TableStruct_mediapipe_2fcalculators_2futil_2flandmarks_5fto_5frender_5fdata_5fcalculator_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// LandmarksToRenderDataCalculatorOptions

// repeated int32 landmark_connections = 1;
inline int LandmarksToRenderDataCalculatorOptions::_internal_landmark_connections_size() const {
  return landmark_connections_.size();
}
inline int LandmarksToRenderDataCalculatorOptions::landmark_connections_size() const {
  return _internal_landmark_connections_size();
}
inline void LandmarksToRenderDataCalculatorOptions::clear_landmark_connections() {
  landmark_connections_.Clear();
}
inline int32_t LandmarksToRenderDataCalculatorOptions::_internal_landmark_connections(int index) const {
  return landmark_connections_.Get(index);
}
inline int32_t LandmarksToRenderDataCalculatorOptions::landmark_connections(int index) const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.landmark_connections)
  return _internal_landmark_connections(index);
}
inline void LandmarksToRenderDataCalculatorOptions::set_landmark_connections(int index, int32_t value) {
  landmark_connections_.Set(index, value);
  // @@protoc_insertion_point(field_set:mediapipe.LandmarksToRenderDataCalculatorOptions.landmark_connections)
}
inline void LandmarksToRenderDataCalculatorOptions::_internal_add_landmark_connections(int32_t value) {
  landmark_connections_.Add(value);
}
inline void LandmarksToRenderDataCalculatorOptions::add_landmark_connections(int32_t value) {
  _internal_add_landmark_connections(value);
  // @@protoc_insertion_point(field_add:mediapipe.LandmarksToRenderDataCalculatorOptions.landmark_connections)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
LandmarksToRenderDataCalculatorOptions::_internal_landmark_connections() const {
  return landmark_connections_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
LandmarksToRenderDataCalculatorOptions::landmark_connections() const {
  // @@protoc_insertion_point(field_list:mediapipe.LandmarksToRenderDataCalculatorOptions.landmark_connections)
  return _internal_landmark_connections();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
LandmarksToRenderDataCalculatorOptions::_internal_mutable_landmark_connections() {
  return &landmark_connections_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
LandmarksToRenderDataCalculatorOptions::mutable_landmark_connections() {
  // @@protoc_insertion_point(field_mutable_list:mediapipe.LandmarksToRenderDataCalculatorOptions.landmark_connections)
  return _internal_mutable_landmark_connections();
}

// optional .mediapipe.Color landmark_color = 2;
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_landmark_color() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || landmark_color_ != nullptr);
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_landmark_color() const {
  return _internal_has_landmark_color();
}
inline const ::mediapipe::Color& LandmarksToRenderDataCalculatorOptions::_internal_landmark_color() const {
  const ::mediapipe::Color* p = landmark_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::mediapipe::Color&>(
      ::mediapipe::_Color_default_instance_);
}
inline const ::mediapipe::Color& LandmarksToRenderDataCalculatorOptions::landmark_color() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.landmark_color)
  return _internal_landmark_color();
}
inline void LandmarksToRenderDataCalculatorOptions::unsafe_arena_set_allocated_landmark_color(
    ::mediapipe::Color* landmark_color) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(landmark_color_);
  }
  landmark_color_ = landmark_color;
  if (landmark_color) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mediapipe.LandmarksToRenderDataCalculatorOptions.landmark_color)
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::release_landmark_color() {
  _has_bits_[0] &= ~0x00000001u;
  ::mediapipe::Color* temp = landmark_color_;
  landmark_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::unsafe_arena_release_landmark_color() {
  // @@protoc_insertion_point(field_release:mediapipe.LandmarksToRenderDataCalculatorOptions.landmark_color)
  _has_bits_[0] &= ~0x00000001u;
  ::mediapipe::Color* temp = landmark_color_;
  landmark_color_ = nullptr;
  return temp;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::_internal_mutable_landmark_color() {
  _has_bits_[0] |= 0x00000001u;
  if (landmark_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::mediapipe::Color>(GetArenaForAllocation());
    landmark_color_ = p;
  }
  return landmark_color_;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::mutable_landmark_color() {
  ::mediapipe::Color* _msg = _internal_mutable_landmark_color();
  // @@protoc_insertion_point(field_mutable:mediapipe.LandmarksToRenderDataCalculatorOptions.landmark_color)
  return _msg;
}
inline void LandmarksToRenderDataCalculatorOptions::set_allocated_landmark_color(::mediapipe::Color* landmark_color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(landmark_color_);
  }
  if (landmark_color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(landmark_color));
    if (message_arena != submessage_arena) {
      landmark_color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, landmark_color, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  landmark_color_ = landmark_color;
  // @@protoc_insertion_point(field_set_allocated:mediapipe.LandmarksToRenderDataCalculatorOptions.landmark_color)
}

// optional .mediapipe.Color connection_color = 3;
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_connection_color() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || connection_color_ != nullptr);
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_connection_color() const {
  return _internal_has_connection_color();
}
inline const ::mediapipe::Color& LandmarksToRenderDataCalculatorOptions::_internal_connection_color() const {
  const ::mediapipe::Color* p = connection_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::mediapipe::Color&>(
      ::mediapipe::_Color_default_instance_);
}
inline const ::mediapipe::Color& LandmarksToRenderDataCalculatorOptions::connection_color() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.connection_color)
  return _internal_connection_color();
}
inline void LandmarksToRenderDataCalculatorOptions::unsafe_arena_set_allocated_connection_color(
    ::mediapipe::Color* connection_color) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(connection_color_);
  }
  connection_color_ = connection_color;
  if (connection_color) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mediapipe.LandmarksToRenderDataCalculatorOptions.connection_color)
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::release_connection_color() {
  _has_bits_[0] &= ~0x00000002u;
  ::mediapipe::Color* temp = connection_color_;
  connection_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::unsafe_arena_release_connection_color() {
  // @@protoc_insertion_point(field_release:mediapipe.LandmarksToRenderDataCalculatorOptions.connection_color)
  _has_bits_[0] &= ~0x00000002u;
  ::mediapipe::Color* temp = connection_color_;
  connection_color_ = nullptr;
  return temp;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::_internal_mutable_connection_color() {
  _has_bits_[0] |= 0x00000002u;
  if (connection_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::mediapipe::Color>(GetArenaForAllocation());
    connection_color_ = p;
  }
  return connection_color_;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::mutable_connection_color() {
  ::mediapipe::Color* _msg = _internal_mutable_connection_color();
  // @@protoc_insertion_point(field_mutable:mediapipe.LandmarksToRenderDataCalculatorOptions.connection_color)
  return _msg;
}
inline void LandmarksToRenderDataCalculatorOptions::set_allocated_connection_color(::mediapipe::Color* connection_color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(connection_color_);
  }
  if (connection_color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(connection_color));
    if (message_arena != submessage_arena) {
      connection_color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, connection_color, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  connection_color_ = connection_color;
  // @@protoc_insertion_point(field_set_allocated:mediapipe.LandmarksToRenderDataCalculatorOptions.connection_color)
}

// optional double thickness = 4 [default = 1];
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_thickness() const {
  bool value = (_has_bits_[0] & 0x00000400u) != 0;
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_thickness() const {
  return _internal_has_thickness();
}
inline void LandmarksToRenderDataCalculatorOptions::clear_thickness() {
  thickness_ = 1;
  _has_bits_[0] &= ~0x00000400u;
}
inline double LandmarksToRenderDataCalculatorOptions::_internal_thickness() const {
  return thickness_;
}
inline double LandmarksToRenderDataCalculatorOptions::thickness() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.thickness)
  return _internal_thickness();
}
inline void LandmarksToRenderDataCalculatorOptions::_internal_set_thickness(double value) {
  _has_bits_[0] |= 0x00000400u;
  thickness_ = value;
}
inline void LandmarksToRenderDataCalculatorOptions::set_thickness(double value) {
  _internal_set_thickness(value);
  // @@protoc_insertion_point(field_set:mediapipe.LandmarksToRenderDataCalculatorOptions.thickness)
}

// optional bool visualize_landmark_depth = 5 [default = true];
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_visualize_landmark_depth() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_visualize_landmark_depth() const {
  return _internal_has_visualize_landmark_depth();
}
inline void LandmarksToRenderDataCalculatorOptions::clear_visualize_landmark_depth() {
  visualize_landmark_depth_ = true;
  _has_bits_[0] &= ~0x00000200u;
}
inline bool LandmarksToRenderDataCalculatorOptions::_internal_visualize_landmark_depth() const {
  return visualize_landmark_depth_;
}
inline bool LandmarksToRenderDataCalculatorOptions::visualize_landmark_depth() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.visualize_landmark_depth)
  return _internal_visualize_landmark_depth();
}
inline void LandmarksToRenderDataCalculatorOptions::_internal_set_visualize_landmark_depth(bool value) {
  _has_bits_[0] |= 0x00000200u;
  visualize_landmark_depth_ = value;
}
inline void LandmarksToRenderDataCalculatorOptions::set_visualize_landmark_depth(bool value) {
  _internal_set_visualize_landmark_depth(value);
  // @@protoc_insertion_point(field_set:mediapipe.LandmarksToRenderDataCalculatorOptions.visualize_landmark_depth)
}

// optional bool utilize_visibility = 6 [default = false];
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_utilize_visibility() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_utilize_visibility() const {
  return _internal_has_utilize_visibility();
}
inline void LandmarksToRenderDataCalculatorOptions::clear_utilize_visibility() {
  utilize_visibility_ = false;
  _has_bits_[0] &= ~0x00000080u;
}
inline bool LandmarksToRenderDataCalculatorOptions::_internal_utilize_visibility() const {
  return utilize_visibility_;
}
inline bool LandmarksToRenderDataCalculatorOptions::utilize_visibility() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.utilize_visibility)
  return _internal_utilize_visibility();
}
inline void LandmarksToRenderDataCalculatorOptions::_internal_set_utilize_visibility(bool value) {
  _has_bits_[0] |= 0x00000080u;
  utilize_visibility_ = value;
}
inline void LandmarksToRenderDataCalculatorOptions::set_utilize_visibility(bool value) {
  _internal_set_utilize_visibility(value);
  // @@protoc_insertion_point(field_set:mediapipe.LandmarksToRenderDataCalculatorOptions.utilize_visibility)
}

// optional double visibility_threshold = 7 [default = 0];
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_visibility_threshold() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_visibility_threshold() const {
  return _internal_has_visibility_threshold();
}
inline void LandmarksToRenderDataCalculatorOptions::clear_visibility_threshold() {
  visibility_threshold_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double LandmarksToRenderDataCalculatorOptions::_internal_visibility_threshold() const {
  return visibility_threshold_;
}
inline double LandmarksToRenderDataCalculatorOptions::visibility_threshold() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.visibility_threshold)
  return _internal_visibility_threshold();
}
inline void LandmarksToRenderDataCalculatorOptions::_internal_set_visibility_threshold(double value) {
  _has_bits_[0] |= 0x00000010u;
  visibility_threshold_ = value;
}
inline void LandmarksToRenderDataCalculatorOptions::set_visibility_threshold(double value) {
  _internal_set_visibility_threshold(value);
  // @@protoc_insertion_point(field_set:mediapipe.LandmarksToRenderDataCalculatorOptions.visibility_threshold)
}

// optional bool utilize_presence = 8 [default = false];
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_utilize_presence() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_utilize_presence() const {
  return _internal_has_utilize_presence();
}
inline void LandmarksToRenderDataCalculatorOptions::clear_utilize_presence() {
  utilize_presence_ = false;
  _has_bits_[0] &= ~0x00000100u;
}
inline bool LandmarksToRenderDataCalculatorOptions::_internal_utilize_presence() const {
  return utilize_presence_;
}
inline bool LandmarksToRenderDataCalculatorOptions::utilize_presence() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.utilize_presence)
  return _internal_utilize_presence();
}
inline void LandmarksToRenderDataCalculatorOptions::_internal_set_utilize_presence(bool value) {
  _has_bits_[0] |= 0x00000100u;
  utilize_presence_ = value;
}
inline void LandmarksToRenderDataCalculatorOptions::set_utilize_presence(bool value) {
  _internal_set_utilize_presence(value);
  // @@protoc_insertion_point(field_set:mediapipe.LandmarksToRenderDataCalculatorOptions.utilize_presence)
}

// optional double presence_threshold = 9 [default = 0];
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_presence_threshold() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_presence_threshold() const {
  return _internal_has_presence_threshold();
}
inline void LandmarksToRenderDataCalculatorOptions::clear_presence_threshold() {
  presence_threshold_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline double LandmarksToRenderDataCalculatorOptions::_internal_presence_threshold() const {
  return presence_threshold_;
}
inline double LandmarksToRenderDataCalculatorOptions::presence_threshold() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.presence_threshold)
  return _internal_presence_threshold();
}
inline void LandmarksToRenderDataCalculatorOptions::_internal_set_presence_threshold(double value) {
  _has_bits_[0] |= 0x00000020u;
  presence_threshold_ = value;
}
inline void LandmarksToRenderDataCalculatorOptions::set_presence_threshold(double value) {
  _internal_set_presence_threshold(value);
  // @@protoc_insertion_point(field_set:mediapipe.LandmarksToRenderDataCalculatorOptions.presence_threshold)
}

// optional double min_depth_circle_thickness = 10 [default = 0];
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_min_depth_circle_thickness() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_min_depth_circle_thickness() const {
  return _internal_has_min_depth_circle_thickness();
}
inline void LandmarksToRenderDataCalculatorOptions::clear_min_depth_circle_thickness() {
  min_depth_circle_thickness_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline double LandmarksToRenderDataCalculatorOptions::_internal_min_depth_circle_thickness() const {
  return min_depth_circle_thickness_;
}
inline double LandmarksToRenderDataCalculatorOptions::min_depth_circle_thickness() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.min_depth_circle_thickness)
  return _internal_min_depth_circle_thickness();
}
inline void LandmarksToRenderDataCalculatorOptions::_internal_set_min_depth_circle_thickness(double value) {
  _has_bits_[0] |= 0x00000040u;
  min_depth_circle_thickness_ = value;
}
inline void LandmarksToRenderDataCalculatorOptions::set_min_depth_circle_thickness(double value) {
  _internal_set_min_depth_circle_thickness(value);
  // @@protoc_insertion_point(field_set:mediapipe.LandmarksToRenderDataCalculatorOptions.min_depth_circle_thickness)
}

// optional double max_depth_circle_thickness = 11 [default = 18];
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_max_depth_circle_thickness() const {
  bool value = (_has_bits_[0] & 0x00000800u) != 0;
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_max_depth_circle_thickness() const {
  return _internal_has_max_depth_circle_thickness();
}
inline void LandmarksToRenderDataCalculatorOptions::clear_max_depth_circle_thickness() {
  max_depth_circle_thickness_ = 18;
  _has_bits_[0] &= ~0x00000800u;
}
inline double LandmarksToRenderDataCalculatorOptions::_internal_max_depth_circle_thickness() const {
  return max_depth_circle_thickness_;
}
inline double LandmarksToRenderDataCalculatorOptions::max_depth_circle_thickness() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.max_depth_circle_thickness)
  return _internal_max_depth_circle_thickness();
}
inline void LandmarksToRenderDataCalculatorOptions::_internal_set_max_depth_circle_thickness(double value) {
  _has_bits_[0] |= 0x00000800u;
  max_depth_circle_thickness_ = value;
}
inline void LandmarksToRenderDataCalculatorOptions::set_max_depth_circle_thickness(double value) {
  _internal_set_max_depth_circle_thickness(value);
  // @@protoc_insertion_point(field_set:mediapipe.LandmarksToRenderDataCalculatorOptions.max_depth_circle_thickness)
}

// optional .mediapipe.Color min_depth_line_color = 12;
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_min_depth_line_color() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || min_depth_line_color_ != nullptr);
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_min_depth_line_color() const {
  return _internal_has_min_depth_line_color();
}
inline const ::mediapipe::Color& LandmarksToRenderDataCalculatorOptions::_internal_min_depth_line_color() const {
  const ::mediapipe::Color* p = min_depth_line_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::mediapipe::Color&>(
      ::mediapipe::_Color_default_instance_);
}
inline const ::mediapipe::Color& LandmarksToRenderDataCalculatorOptions::min_depth_line_color() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.min_depth_line_color)
  return _internal_min_depth_line_color();
}
inline void LandmarksToRenderDataCalculatorOptions::unsafe_arena_set_allocated_min_depth_line_color(
    ::mediapipe::Color* min_depth_line_color) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(min_depth_line_color_);
  }
  min_depth_line_color_ = min_depth_line_color;
  if (min_depth_line_color) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mediapipe.LandmarksToRenderDataCalculatorOptions.min_depth_line_color)
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::release_min_depth_line_color() {
  _has_bits_[0] &= ~0x00000004u;
  ::mediapipe::Color* temp = min_depth_line_color_;
  min_depth_line_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::unsafe_arena_release_min_depth_line_color() {
  // @@protoc_insertion_point(field_release:mediapipe.LandmarksToRenderDataCalculatorOptions.min_depth_line_color)
  _has_bits_[0] &= ~0x00000004u;
  ::mediapipe::Color* temp = min_depth_line_color_;
  min_depth_line_color_ = nullptr;
  return temp;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::_internal_mutable_min_depth_line_color() {
  _has_bits_[0] |= 0x00000004u;
  if (min_depth_line_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::mediapipe::Color>(GetArenaForAllocation());
    min_depth_line_color_ = p;
  }
  return min_depth_line_color_;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::mutable_min_depth_line_color() {
  ::mediapipe::Color* _msg = _internal_mutable_min_depth_line_color();
  // @@protoc_insertion_point(field_mutable:mediapipe.LandmarksToRenderDataCalculatorOptions.min_depth_line_color)
  return _msg;
}
inline void LandmarksToRenderDataCalculatorOptions::set_allocated_min_depth_line_color(::mediapipe::Color* min_depth_line_color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(min_depth_line_color_);
  }
  if (min_depth_line_color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(min_depth_line_color));
    if (message_arena != submessage_arena) {
      min_depth_line_color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, min_depth_line_color, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  min_depth_line_color_ = min_depth_line_color;
  // @@protoc_insertion_point(field_set_allocated:mediapipe.LandmarksToRenderDataCalculatorOptions.min_depth_line_color)
}

// optional .mediapipe.Color max_depth_line_color = 13;
inline bool LandmarksToRenderDataCalculatorOptions::_internal_has_max_depth_line_color() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || max_depth_line_color_ != nullptr);
  return value;
}
inline bool LandmarksToRenderDataCalculatorOptions::has_max_depth_line_color() const {
  return _internal_has_max_depth_line_color();
}
inline const ::mediapipe::Color& LandmarksToRenderDataCalculatorOptions::_internal_max_depth_line_color() const {
  const ::mediapipe::Color* p = max_depth_line_color_;
  return p != nullptr ? *p : reinterpret_cast<const ::mediapipe::Color&>(
      ::mediapipe::_Color_default_instance_);
}
inline const ::mediapipe::Color& LandmarksToRenderDataCalculatorOptions::max_depth_line_color() const {
  // @@protoc_insertion_point(field_get:mediapipe.LandmarksToRenderDataCalculatorOptions.max_depth_line_color)
  return _internal_max_depth_line_color();
}
inline void LandmarksToRenderDataCalculatorOptions::unsafe_arena_set_allocated_max_depth_line_color(
    ::mediapipe::Color* max_depth_line_color) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(max_depth_line_color_);
  }
  max_depth_line_color_ = max_depth_line_color;
  if (max_depth_line_color) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mediapipe.LandmarksToRenderDataCalculatorOptions.max_depth_line_color)
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::release_max_depth_line_color() {
  _has_bits_[0] &= ~0x00000008u;
  ::mediapipe::Color* temp = max_depth_line_color_;
  max_depth_line_color_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::unsafe_arena_release_max_depth_line_color() {
  // @@protoc_insertion_point(field_release:mediapipe.LandmarksToRenderDataCalculatorOptions.max_depth_line_color)
  _has_bits_[0] &= ~0x00000008u;
  ::mediapipe::Color* temp = max_depth_line_color_;
  max_depth_line_color_ = nullptr;
  return temp;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::_internal_mutable_max_depth_line_color() {
  _has_bits_[0] |= 0x00000008u;
  if (max_depth_line_color_ == nullptr) {
    auto* p = CreateMaybeMessage<::mediapipe::Color>(GetArenaForAllocation());
    max_depth_line_color_ = p;
  }
  return max_depth_line_color_;
}
inline ::mediapipe::Color* LandmarksToRenderDataCalculatorOptions::mutable_max_depth_line_color() {
  ::mediapipe::Color* _msg = _internal_mutable_max_depth_line_color();
  // @@protoc_insertion_point(field_mutable:mediapipe.LandmarksToRenderDataCalculatorOptions.max_depth_line_color)
  return _msg;
}
inline void LandmarksToRenderDataCalculatorOptions::set_allocated_max_depth_line_color(::mediapipe::Color* max_depth_line_color) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(max_depth_line_color_);
  }
  if (max_depth_line_color) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(max_depth_line_color));
    if (message_arena != submessage_arena) {
      max_depth_line_color = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, max_depth_line_color, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  max_depth_line_color_ = max_depth_line_color;
  // @@protoc_insertion_point(field_set_allocated:mediapipe.LandmarksToRenderDataCalculatorOptions.max_depth_line_color)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace mediapipe

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mediapipe_2fcalculators_2futil_2flandmarks_5fto_5frender_5fdata_5fcalculator_2eproto
