// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mediapipe/modules/holistic_landmark/calculators/roi_tracking_calculator.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_mediapipe_2fmodules_2fholistic_5flandmark_2fcalculators_2froi_5ftracking_5fcalculator_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_mediapipe_2fmodules_2fholistic_5flandmark_2fcalculators_2froi_5ftracking_5fcalculator_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "mediapipe/framework/calculator.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_mediapipe_2fmodules_2fholistic_5flandmark_2fcalculators_2froi_5ftracking_5fcalculator_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_mediapipe_2fmodules_2fholistic_5flandmark_2fcalculators_2froi_5ftracking_5fcalculator_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_mediapipe_2fmodules_2fholistic_5flandmark_2fcalculators_2froi_5ftracking_5fcalculator_2eproto;
namespace mediapipe {
class RoiTrackingCalculatorOptions;
struct RoiTrackingCalculatorOptionsDefaultTypeInternal;
extern RoiTrackingCalculatorOptionsDefaultTypeInternal _RoiTrackingCalculatorOptions_default_instance_;
class RoiTrackingCalculatorOptions_IouRequirements;
struct RoiTrackingCalculatorOptions_IouRequirementsDefaultTypeInternal;
extern RoiTrackingCalculatorOptions_IouRequirementsDefaultTypeInternal _RoiTrackingCalculatorOptions_IouRequirements_default_instance_;
class RoiTrackingCalculatorOptions_LandmarksRequirements;
struct RoiTrackingCalculatorOptions_LandmarksRequirementsDefaultTypeInternal;
extern RoiTrackingCalculatorOptions_LandmarksRequirementsDefaultTypeInternal _RoiTrackingCalculatorOptions_LandmarksRequirements_default_instance_;
class RoiTrackingCalculatorOptions_RectRequirements;
struct RoiTrackingCalculatorOptions_RectRequirementsDefaultTypeInternal;
extern RoiTrackingCalculatorOptions_RectRequirementsDefaultTypeInternal _RoiTrackingCalculatorOptions_RectRequirements_default_instance_;
}  // namespace mediapipe
PROTOBUF_NAMESPACE_OPEN
template<> ::mediapipe::RoiTrackingCalculatorOptions* Arena::CreateMaybeMessage<::mediapipe::RoiTrackingCalculatorOptions>(Arena*);
template<> ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* Arena::CreateMaybeMessage<::mediapipe::RoiTrackingCalculatorOptions_IouRequirements>(Arena*);
template<> ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* Arena::CreateMaybeMessage<::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements>(Arena*);
template<> ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* Arena::CreateMaybeMessage<::mediapipe::RoiTrackingCalculatorOptions_RectRequirements>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mediapipe {

// ===================================================================

class RoiTrackingCalculatorOptions_IouRequirements final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mediapipe.RoiTrackingCalculatorOptions.IouRequirements) */ {
 public:
  inline RoiTrackingCalculatorOptions_IouRequirements() : RoiTrackingCalculatorOptions_IouRequirements(nullptr) {}
  ~RoiTrackingCalculatorOptions_IouRequirements() override;
  explicit constexpr RoiTrackingCalculatorOptions_IouRequirements(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoiTrackingCalculatorOptions_IouRequirements(const RoiTrackingCalculatorOptions_IouRequirements& from);
  RoiTrackingCalculatorOptions_IouRequirements(RoiTrackingCalculatorOptions_IouRequirements&& from) noexcept
    : RoiTrackingCalculatorOptions_IouRequirements() {
    *this = ::std::move(from);
  }

  inline RoiTrackingCalculatorOptions_IouRequirements& operator=(const RoiTrackingCalculatorOptions_IouRequirements& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoiTrackingCalculatorOptions_IouRequirements& operator=(RoiTrackingCalculatorOptions_IouRequirements&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoiTrackingCalculatorOptions_IouRequirements& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoiTrackingCalculatorOptions_IouRequirements* internal_default_instance() {
    return reinterpret_cast<const RoiTrackingCalculatorOptions_IouRequirements*>(
               &_RoiTrackingCalculatorOptions_IouRequirements_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RoiTrackingCalculatorOptions_IouRequirements& a, RoiTrackingCalculatorOptions_IouRequirements& b) {
    a.Swap(&b);
  }
  inline void Swap(RoiTrackingCalculatorOptions_IouRequirements* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoiTrackingCalculatorOptions_IouRequirements* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoiTrackingCalculatorOptions_IouRequirements* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoiTrackingCalculatorOptions_IouRequirements>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoiTrackingCalculatorOptions_IouRequirements& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RoiTrackingCalculatorOptions_IouRequirements& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoiTrackingCalculatorOptions_IouRequirements* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mediapipe.RoiTrackingCalculatorOptions.IouRequirements";
  }
  protected:
  explicit RoiTrackingCalculatorOptions_IouRequirements(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMinIouFieldNumber = 1,
  };
  // optional float min_iou = 1 [default = 0.5];
  bool has_min_iou() const;
  private:
  bool _internal_has_min_iou() const;
  public:
  void clear_min_iou();
  float min_iou() const;
  void set_min_iou(float value);
  private:
  float _internal_min_iou() const;
  void _internal_set_min_iou(float value);
  public:

  // @@protoc_insertion_point(class_scope:mediapipe.RoiTrackingCalculatorOptions.IouRequirements)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  float min_iou_;
  friend struct ::TableStruct_mediapipe_2fmodules_2fholistic_5flandmark_2fcalculators_2froi_5ftracking_5fcalculator_2eproto;
};
// -------------------------------------------------------------------

class RoiTrackingCalculatorOptions_RectRequirements final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mediapipe.RoiTrackingCalculatorOptions.RectRequirements) */ {
 public:
  inline RoiTrackingCalculatorOptions_RectRequirements() : RoiTrackingCalculatorOptions_RectRequirements(nullptr) {}
  ~RoiTrackingCalculatorOptions_RectRequirements() override;
  explicit constexpr RoiTrackingCalculatorOptions_RectRequirements(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoiTrackingCalculatorOptions_RectRequirements(const RoiTrackingCalculatorOptions_RectRequirements& from);
  RoiTrackingCalculatorOptions_RectRequirements(RoiTrackingCalculatorOptions_RectRequirements&& from) noexcept
    : RoiTrackingCalculatorOptions_RectRequirements() {
    *this = ::std::move(from);
  }

  inline RoiTrackingCalculatorOptions_RectRequirements& operator=(const RoiTrackingCalculatorOptions_RectRequirements& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoiTrackingCalculatorOptions_RectRequirements& operator=(RoiTrackingCalculatorOptions_RectRequirements&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoiTrackingCalculatorOptions_RectRequirements& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoiTrackingCalculatorOptions_RectRequirements* internal_default_instance() {
    return reinterpret_cast<const RoiTrackingCalculatorOptions_RectRequirements*>(
               &_RoiTrackingCalculatorOptions_RectRequirements_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RoiTrackingCalculatorOptions_RectRequirements& a, RoiTrackingCalculatorOptions_RectRequirements& b) {
    a.Swap(&b);
  }
  inline void Swap(RoiTrackingCalculatorOptions_RectRequirements* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoiTrackingCalculatorOptions_RectRequirements* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoiTrackingCalculatorOptions_RectRequirements* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoiTrackingCalculatorOptions_RectRequirements>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoiTrackingCalculatorOptions_RectRequirements& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RoiTrackingCalculatorOptions_RectRequirements& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoiTrackingCalculatorOptions_RectRequirements* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mediapipe.RoiTrackingCalculatorOptions.RectRequirements";
  }
  protected:
  explicit RoiTrackingCalculatorOptions_RectRequirements(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScaleFieldNumber = 3,
    kRotationDegreesFieldNumber = 1,
    kTranslationFieldNumber = 2,
  };
  // optional float scale = 3 [default = 0.1];
  bool has_scale() const;
  private:
  bool _internal_has_scale() const;
  public:
  void clear_scale();
  float scale() const;
  void set_scale(float value);
  private:
  float _internal_scale() const;
  void _internal_set_scale(float value);
  public:

  // optional float rotation_degrees = 1 [default = 10];
  bool has_rotation_degrees() const;
  private:
  bool _internal_has_rotation_degrees() const;
  public:
  void clear_rotation_degrees();
  float rotation_degrees() const;
  void set_rotation_degrees(float value);
  private:
  float _internal_rotation_degrees() const;
  void _internal_set_rotation_degrees(float value);
  public:

  // optional float translation = 2 [default = 0.1];
  bool has_translation() const;
  private:
  bool _internal_has_translation() const;
  public:
  void clear_translation();
  float translation() const;
  void set_translation(float value);
  private:
  float _internal_translation() const;
  void _internal_set_translation(float value);
  public:

  // @@protoc_insertion_point(class_scope:mediapipe.RoiTrackingCalculatorOptions.RectRequirements)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  float scale_;
  float rotation_degrees_;
  float translation_;
  friend struct ::TableStruct_mediapipe_2fmodules_2fholistic_5flandmark_2fcalculators_2froi_5ftracking_5fcalculator_2eproto;
};
// -------------------------------------------------------------------

class RoiTrackingCalculatorOptions_LandmarksRequirements final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mediapipe.RoiTrackingCalculatorOptions.LandmarksRequirements) */ {
 public:
  inline RoiTrackingCalculatorOptions_LandmarksRequirements() : RoiTrackingCalculatorOptions_LandmarksRequirements(nullptr) {}
  ~RoiTrackingCalculatorOptions_LandmarksRequirements() override;
  explicit constexpr RoiTrackingCalculatorOptions_LandmarksRequirements(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoiTrackingCalculatorOptions_LandmarksRequirements(const RoiTrackingCalculatorOptions_LandmarksRequirements& from);
  RoiTrackingCalculatorOptions_LandmarksRequirements(RoiTrackingCalculatorOptions_LandmarksRequirements&& from) noexcept
    : RoiTrackingCalculatorOptions_LandmarksRequirements() {
    *this = ::std::move(from);
  }

  inline RoiTrackingCalculatorOptions_LandmarksRequirements& operator=(const RoiTrackingCalculatorOptions_LandmarksRequirements& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoiTrackingCalculatorOptions_LandmarksRequirements& operator=(RoiTrackingCalculatorOptions_LandmarksRequirements&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoiTrackingCalculatorOptions_LandmarksRequirements& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoiTrackingCalculatorOptions_LandmarksRequirements* internal_default_instance() {
    return reinterpret_cast<const RoiTrackingCalculatorOptions_LandmarksRequirements*>(
               &_RoiTrackingCalculatorOptions_LandmarksRequirements_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(RoiTrackingCalculatorOptions_LandmarksRequirements& a, RoiTrackingCalculatorOptions_LandmarksRequirements& b) {
    a.Swap(&b);
  }
  inline void Swap(RoiTrackingCalculatorOptions_LandmarksRequirements* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoiTrackingCalculatorOptions_LandmarksRequirements* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoiTrackingCalculatorOptions_LandmarksRequirements* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoiTrackingCalculatorOptions_LandmarksRequirements>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoiTrackingCalculatorOptions_LandmarksRequirements& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RoiTrackingCalculatorOptions_LandmarksRequirements& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoiTrackingCalculatorOptions_LandmarksRequirements* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mediapipe.RoiTrackingCalculatorOptions.LandmarksRequirements";
  }
  protected:
  explicit RoiTrackingCalculatorOptions_LandmarksRequirements(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRecropRectMarginFieldNumber = 1,
  };
  // optional float recrop_rect_margin = 1 [default = 0];
  bool has_recrop_rect_margin() const;
  private:
  bool _internal_has_recrop_rect_margin() const;
  public:
  void clear_recrop_rect_margin();
  float recrop_rect_margin() const;
  void set_recrop_rect_margin(float value);
  private:
  float _internal_recrop_rect_margin() const;
  void _internal_set_recrop_rect_margin(float value);
  public:

  // @@protoc_insertion_point(class_scope:mediapipe.RoiTrackingCalculatorOptions.LandmarksRequirements)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  float recrop_rect_margin_;
  friend struct ::TableStruct_mediapipe_2fmodules_2fholistic_5flandmark_2fcalculators_2froi_5ftracking_5fcalculator_2eproto;
};
// -------------------------------------------------------------------

class RoiTrackingCalculatorOptions final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mediapipe.RoiTrackingCalculatorOptions) */ {
 public:
  inline RoiTrackingCalculatorOptions() : RoiTrackingCalculatorOptions(nullptr) {}
  ~RoiTrackingCalculatorOptions() override;
  explicit constexpr RoiTrackingCalculatorOptions(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  RoiTrackingCalculatorOptions(const RoiTrackingCalculatorOptions& from);
  RoiTrackingCalculatorOptions(RoiTrackingCalculatorOptions&& from) noexcept
    : RoiTrackingCalculatorOptions() {
    *this = ::std::move(from);
  }

  inline RoiTrackingCalculatorOptions& operator=(const RoiTrackingCalculatorOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoiTrackingCalculatorOptions& operator=(RoiTrackingCalculatorOptions&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RoiTrackingCalculatorOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const RoiTrackingCalculatorOptions* internal_default_instance() {
    return reinterpret_cast<const RoiTrackingCalculatorOptions*>(
               &_RoiTrackingCalculatorOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(RoiTrackingCalculatorOptions& a, RoiTrackingCalculatorOptions& b) {
    a.Swap(&b);
  }
  inline void Swap(RoiTrackingCalculatorOptions* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RoiTrackingCalculatorOptions* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RoiTrackingCalculatorOptions* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RoiTrackingCalculatorOptions>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const RoiTrackingCalculatorOptions& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const RoiTrackingCalculatorOptions& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoiTrackingCalculatorOptions* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mediapipe.RoiTrackingCalculatorOptions";
  }
  protected:
  explicit RoiTrackingCalculatorOptions(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef RoiTrackingCalculatorOptions_IouRequirements IouRequirements;
  typedef RoiTrackingCalculatorOptions_RectRequirements RectRequirements;
  typedef RoiTrackingCalculatorOptions_LandmarksRequirements LandmarksRequirements;

  // accessors -------------------------------------------------------

  enum : int {
    kIouRequirementsFieldNumber = 1,
    kRectRequirementsFieldNumber = 2,
    kLandmarksRequirementsFieldNumber = 3,
  };
  // optional .mediapipe.RoiTrackingCalculatorOptions.IouRequirements iou_requirements = 1;
  bool has_iou_requirements() const;
  private:
  bool _internal_has_iou_requirements() const;
  public:
  void clear_iou_requirements();
  const ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements& iou_requirements() const;
  PROTOBUF_NODISCARD ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* release_iou_requirements();
  ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* mutable_iou_requirements();
  void set_allocated_iou_requirements(::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* iou_requirements);
  private:
  const ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements& _internal_iou_requirements() const;
  ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* _internal_mutable_iou_requirements();
  public:
  void unsafe_arena_set_allocated_iou_requirements(
      ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* iou_requirements);
  ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* unsafe_arena_release_iou_requirements();

  // optional .mediapipe.RoiTrackingCalculatorOptions.RectRequirements rect_requirements = 2;
  bool has_rect_requirements() const;
  private:
  bool _internal_has_rect_requirements() const;
  public:
  void clear_rect_requirements();
  const ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements& rect_requirements() const;
  PROTOBUF_NODISCARD ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* release_rect_requirements();
  ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* mutable_rect_requirements();
  void set_allocated_rect_requirements(::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* rect_requirements);
  private:
  const ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements& _internal_rect_requirements() const;
  ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* _internal_mutable_rect_requirements();
  public:
  void unsafe_arena_set_allocated_rect_requirements(
      ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* rect_requirements);
  ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* unsafe_arena_release_rect_requirements();

  // optional .mediapipe.RoiTrackingCalculatorOptions.LandmarksRequirements landmarks_requirements = 3;
  bool has_landmarks_requirements() const;
  private:
  bool _internal_has_landmarks_requirements() const;
  public:
  void clear_landmarks_requirements();
  const ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements& landmarks_requirements() const;
  PROTOBUF_NODISCARD ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* release_landmarks_requirements();
  ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* mutable_landmarks_requirements();
  void set_allocated_landmarks_requirements(::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* landmarks_requirements);
  private:
  const ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements& _internal_landmarks_requirements() const;
  ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* _internal_mutable_landmarks_requirements();
  public:
  void unsafe_arena_set_allocated_landmarks_requirements(
      ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* landmarks_requirements);
  ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* unsafe_arena_release_landmarks_requirements();

  static const int kExtFieldNumber = 329994630;
  static ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::mediapipe::CalculatorOptions,
      ::PROTOBUF_NAMESPACE_ID::internal::MessageTypeTraits< ::mediapipe::RoiTrackingCalculatorOptions >, 11, false >
    ext;
  // @@protoc_insertion_point(class_scope:mediapipe.RoiTrackingCalculatorOptions)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* iou_requirements_;
  ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* rect_requirements_;
  ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* landmarks_requirements_;
  friend struct ::TableStruct_mediapipe_2fmodules_2fholistic_5flandmark_2fcalculators_2froi_5ftracking_5fcalculator_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoiTrackingCalculatorOptions_IouRequirements

// optional float min_iou = 1 [default = 0.5];
inline bool RoiTrackingCalculatorOptions_IouRequirements::_internal_has_min_iou() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RoiTrackingCalculatorOptions_IouRequirements::has_min_iou() const {
  return _internal_has_min_iou();
}
inline void RoiTrackingCalculatorOptions_IouRequirements::clear_min_iou() {
  min_iou_ = 0.5f;
  _has_bits_[0] &= ~0x00000001u;
}
inline float RoiTrackingCalculatorOptions_IouRequirements::_internal_min_iou() const {
  return min_iou_;
}
inline float RoiTrackingCalculatorOptions_IouRequirements::min_iou() const {
  // @@protoc_insertion_point(field_get:mediapipe.RoiTrackingCalculatorOptions.IouRequirements.min_iou)
  return _internal_min_iou();
}
inline void RoiTrackingCalculatorOptions_IouRequirements::_internal_set_min_iou(float value) {
  _has_bits_[0] |= 0x00000001u;
  min_iou_ = value;
}
inline void RoiTrackingCalculatorOptions_IouRequirements::set_min_iou(float value) {
  _internal_set_min_iou(value);
  // @@protoc_insertion_point(field_set:mediapipe.RoiTrackingCalculatorOptions.IouRequirements.min_iou)
}

// -------------------------------------------------------------------

// RoiTrackingCalculatorOptions_RectRequirements

// optional float rotation_degrees = 1 [default = 10];
inline bool RoiTrackingCalculatorOptions_RectRequirements::_internal_has_rotation_degrees() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RoiTrackingCalculatorOptions_RectRequirements::has_rotation_degrees() const {
  return _internal_has_rotation_degrees();
}
inline void RoiTrackingCalculatorOptions_RectRequirements::clear_rotation_degrees() {
  rotation_degrees_ = 10;
  _has_bits_[0] &= ~0x00000002u;
}
inline float RoiTrackingCalculatorOptions_RectRequirements::_internal_rotation_degrees() const {
  return rotation_degrees_;
}
inline float RoiTrackingCalculatorOptions_RectRequirements::rotation_degrees() const {
  // @@protoc_insertion_point(field_get:mediapipe.RoiTrackingCalculatorOptions.RectRequirements.rotation_degrees)
  return _internal_rotation_degrees();
}
inline void RoiTrackingCalculatorOptions_RectRequirements::_internal_set_rotation_degrees(float value) {
  _has_bits_[0] |= 0x00000002u;
  rotation_degrees_ = value;
}
inline void RoiTrackingCalculatorOptions_RectRequirements::set_rotation_degrees(float value) {
  _internal_set_rotation_degrees(value);
  // @@protoc_insertion_point(field_set:mediapipe.RoiTrackingCalculatorOptions.RectRequirements.rotation_degrees)
}

// optional float translation = 2 [default = 0.1];
inline bool RoiTrackingCalculatorOptions_RectRequirements::_internal_has_translation() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool RoiTrackingCalculatorOptions_RectRequirements::has_translation() const {
  return _internal_has_translation();
}
inline void RoiTrackingCalculatorOptions_RectRequirements::clear_translation() {
  translation_ = 0.1f;
  _has_bits_[0] &= ~0x00000004u;
}
inline float RoiTrackingCalculatorOptions_RectRequirements::_internal_translation() const {
  return translation_;
}
inline float RoiTrackingCalculatorOptions_RectRequirements::translation() const {
  // @@protoc_insertion_point(field_get:mediapipe.RoiTrackingCalculatorOptions.RectRequirements.translation)
  return _internal_translation();
}
inline void RoiTrackingCalculatorOptions_RectRequirements::_internal_set_translation(float value) {
  _has_bits_[0] |= 0x00000004u;
  translation_ = value;
}
inline void RoiTrackingCalculatorOptions_RectRequirements::set_translation(float value) {
  _internal_set_translation(value);
  // @@protoc_insertion_point(field_set:mediapipe.RoiTrackingCalculatorOptions.RectRequirements.translation)
}

// optional float scale = 3 [default = 0.1];
inline bool RoiTrackingCalculatorOptions_RectRequirements::_internal_has_scale() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RoiTrackingCalculatorOptions_RectRequirements::has_scale() const {
  return _internal_has_scale();
}
inline void RoiTrackingCalculatorOptions_RectRequirements::clear_scale() {
  scale_ = 0.1f;
  _has_bits_[0] &= ~0x00000001u;
}
inline float RoiTrackingCalculatorOptions_RectRequirements::_internal_scale() const {
  return scale_;
}
inline float RoiTrackingCalculatorOptions_RectRequirements::scale() const {
  // @@protoc_insertion_point(field_get:mediapipe.RoiTrackingCalculatorOptions.RectRequirements.scale)
  return _internal_scale();
}
inline void RoiTrackingCalculatorOptions_RectRequirements::_internal_set_scale(float value) {
  _has_bits_[0] |= 0x00000001u;
  scale_ = value;
}
inline void RoiTrackingCalculatorOptions_RectRequirements::set_scale(float value) {
  _internal_set_scale(value);
  // @@protoc_insertion_point(field_set:mediapipe.RoiTrackingCalculatorOptions.RectRequirements.scale)
}

// -------------------------------------------------------------------

// RoiTrackingCalculatorOptions_LandmarksRequirements

// optional float recrop_rect_margin = 1 [default = 0];
inline bool RoiTrackingCalculatorOptions_LandmarksRequirements::_internal_has_recrop_rect_margin() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RoiTrackingCalculatorOptions_LandmarksRequirements::has_recrop_rect_margin() const {
  return _internal_has_recrop_rect_margin();
}
inline void RoiTrackingCalculatorOptions_LandmarksRequirements::clear_recrop_rect_margin() {
  recrop_rect_margin_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline float RoiTrackingCalculatorOptions_LandmarksRequirements::_internal_recrop_rect_margin() const {
  return recrop_rect_margin_;
}
inline float RoiTrackingCalculatorOptions_LandmarksRequirements::recrop_rect_margin() const {
  // @@protoc_insertion_point(field_get:mediapipe.RoiTrackingCalculatorOptions.LandmarksRequirements.recrop_rect_margin)
  return _internal_recrop_rect_margin();
}
inline void RoiTrackingCalculatorOptions_LandmarksRequirements::_internal_set_recrop_rect_margin(float value) {
  _has_bits_[0] |= 0x00000001u;
  recrop_rect_margin_ = value;
}
inline void RoiTrackingCalculatorOptions_LandmarksRequirements::set_recrop_rect_margin(float value) {
  _internal_set_recrop_rect_margin(value);
  // @@protoc_insertion_point(field_set:mediapipe.RoiTrackingCalculatorOptions.LandmarksRequirements.recrop_rect_margin)
}

// -------------------------------------------------------------------

// RoiTrackingCalculatorOptions

// optional .mediapipe.RoiTrackingCalculatorOptions.IouRequirements iou_requirements = 1;
inline bool RoiTrackingCalculatorOptions::_internal_has_iou_requirements() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || iou_requirements_ != nullptr);
  return value;
}
inline bool RoiTrackingCalculatorOptions::has_iou_requirements() const {
  return _internal_has_iou_requirements();
}
inline void RoiTrackingCalculatorOptions::clear_iou_requirements() {
  if (iou_requirements_ != nullptr) iou_requirements_->Clear();
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements& RoiTrackingCalculatorOptions::_internal_iou_requirements() const {
  const ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* p = iou_requirements_;
  return p != nullptr ? *p : reinterpret_cast<const ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements&>(
      ::mediapipe::_RoiTrackingCalculatorOptions_IouRequirements_default_instance_);
}
inline const ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements& RoiTrackingCalculatorOptions::iou_requirements() const {
  // @@protoc_insertion_point(field_get:mediapipe.RoiTrackingCalculatorOptions.iou_requirements)
  return _internal_iou_requirements();
}
inline void RoiTrackingCalculatorOptions::unsafe_arena_set_allocated_iou_requirements(
    ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* iou_requirements) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(iou_requirements_);
  }
  iou_requirements_ = iou_requirements;
  if (iou_requirements) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mediapipe.RoiTrackingCalculatorOptions.iou_requirements)
}
inline ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* RoiTrackingCalculatorOptions::release_iou_requirements() {
  _has_bits_[0] &= ~0x00000001u;
  ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* temp = iou_requirements_;
  iou_requirements_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* RoiTrackingCalculatorOptions::unsafe_arena_release_iou_requirements() {
  // @@protoc_insertion_point(field_release:mediapipe.RoiTrackingCalculatorOptions.iou_requirements)
  _has_bits_[0] &= ~0x00000001u;
  ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* temp = iou_requirements_;
  iou_requirements_ = nullptr;
  return temp;
}
inline ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* RoiTrackingCalculatorOptions::_internal_mutable_iou_requirements() {
  _has_bits_[0] |= 0x00000001u;
  if (iou_requirements_ == nullptr) {
    auto* p = CreateMaybeMessage<::mediapipe::RoiTrackingCalculatorOptions_IouRequirements>(GetArenaForAllocation());
    iou_requirements_ = p;
  }
  return iou_requirements_;
}
inline ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* RoiTrackingCalculatorOptions::mutable_iou_requirements() {
  ::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* _msg = _internal_mutable_iou_requirements();
  // @@protoc_insertion_point(field_mutable:mediapipe.RoiTrackingCalculatorOptions.iou_requirements)
  return _msg;
}
inline void RoiTrackingCalculatorOptions::set_allocated_iou_requirements(::mediapipe::RoiTrackingCalculatorOptions_IouRequirements* iou_requirements) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete iou_requirements_;
  }
  if (iou_requirements) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::mediapipe::RoiTrackingCalculatorOptions_IouRequirements>::GetOwningArena(iou_requirements);
    if (message_arena != submessage_arena) {
      iou_requirements = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, iou_requirements, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  iou_requirements_ = iou_requirements;
  // @@protoc_insertion_point(field_set_allocated:mediapipe.RoiTrackingCalculatorOptions.iou_requirements)
}

// optional .mediapipe.RoiTrackingCalculatorOptions.RectRequirements rect_requirements = 2;
inline bool RoiTrackingCalculatorOptions::_internal_has_rect_requirements() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || rect_requirements_ != nullptr);
  return value;
}
inline bool RoiTrackingCalculatorOptions::has_rect_requirements() const {
  return _internal_has_rect_requirements();
}
inline void RoiTrackingCalculatorOptions::clear_rect_requirements() {
  if (rect_requirements_ != nullptr) rect_requirements_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements& RoiTrackingCalculatorOptions::_internal_rect_requirements() const {
  const ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* p = rect_requirements_;
  return p != nullptr ? *p : reinterpret_cast<const ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements&>(
      ::mediapipe::_RoiTrackingCalculatorOptions_RectRequirements_default_instance_);
}
inline const ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements& RoiTrackingCalculatorOptions::rect_requirements() const {
  // @@protoc_insertion_point(field_get:mediapipe.RoiTrackingCalculatorOptions.rect_requirements)
  return _internal_rect_requirements();
}
inline void RoiTrackingCalculatorOptions::unsafe_arena_set_allocated_rect_requirements(
    ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* rect_requirements) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(rect_requirements_);
  }
  rect_requirements_ = rect_requirements;
  if (rect_requirements) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mediapipe.RoiTrackingCalculatorOptions.rect_requirements)
}
inline ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* RoiTrackingCalculatorOptions::release_rect_requirements() {
  _has_bits_[0] &= ~0x00000002u;
  ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* temp = rect_requirements_;
  rect_requirements_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* RoiTrackingCalculatorOptions::unsafe_arena_release_rect_requirements() {
  // @@protoc_insertion_point(field_release:mediapipe.RoiTrackingCalculatorOptions.rect_requirements)
  _has_bits_[0] &= ~0x00000002u;
  ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* temp = rect_requirements_;
  rect_requirements_ = nullptr;
  return temp;
}
inline ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* RoiTrackingCalculatorOptions::_internal_mutable_rect_requirements() {
  _has_bits_[0] |= 0x00000002u;
  if (rect_requirements_ == nullptr) {
    auto* p = CreateMaybeMessage<::mediapipe::RoiTrackingCalculatorOptions_RectRequirements>(GetArenaForAllocation());
    rect_requirements_ = p;
  }
  return rect_requirements_;
}
inline ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* RoiTrackingCalculatorOptions::mutable_rect_requirements() {
  ::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* _msg = _internal_mutable_rect_requirements();
  // @@protoc_insertion_point(field_mutable:mediapipe.RoiTrackingCalculatorOptions.rect_requirements)
  return _msg;
}
inline void RoiTrackingCalculatorOptions::set_allocated_rect_requirements(::mediapipe::RoiTrackingCalculatorOptions_RectRequirements* rect_requirements) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete rect_requirements_;
  }
  if (rect_requirements) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::mediapipe::RoiTrackingCalculatorOptions_RectRequirements>::GetOwningArena(rect_requirements);
    if (message_arena != submessage_arena) {
      rect_requirements = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, rect_requirements, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  rect_requirements_ = rect_requirements;
  // @@protoc_insertion_point(field_set_allocated:mediapipe.RoiTrackingCalculatorOptions.rect_requirements)
}

// optional .mediapipe.RoiTrackingCalculatorOptions.LandmarksRequirements landmarks_requirements = 3;
inline bool RoiTrackingCalculatorOptions::_internal_has_landmarks_requirements() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || landmarks_requirements_ != nullptr);
  return value;
}
inline bool RoiTrackingCalculatorOptions::has_landmarks_requirements() const {
  return _internal_has_landmarks_requirements();
}
inline void RoiTrackingCalculatorOptions::clear_landmarks_requirements() {
  if (landmarks_requirements_ != nullptr) landmarks_requirements_->Clear();
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements& RoiTrackingCalculatorOptions::_internal_landmarks_requirements() const {
  const ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* p = landmarks_requirements_;
  return p != nullptr ? *p : reinterpret_cast<const ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements&>(
      ::mediapipe::_RoiTrackingCalculatorOptions_LandmarksRequirements_default_instance_);
}
inline const ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements& RoiTrackingCalculatorOptions::landmarks_requirements() const {
  // @@protoc_insertion_point(field_get:mediapipe.RoiTrackingCalculatorOptions.landmarks_requirements)
  return _internal_landmarks_requirements();
}
inline void RoiTrackingCalculatorOptions::unsafe_arena_set_allocated_landmarks_requirements(
    ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* landmarks_requirements) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(landmarks_requirements_);
  }
  landmarks_requirements_ = landmarks_requirements;
  if (landmarks_requirements) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:mediapipe.RoiTrackingCalculatorOptions.landmarks_requirements)
}
inline ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* RoiTrackingCalculatorOptions::release_landmarks_requirements() {
  _has_bits_[0] &= ~0x00000004u;
  ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* temp = landmarks_requirements_;
  landmarks_requirements_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* RoiTrackingCalculatorOptions::unsafe_arena_release_landmarks_requirements() {
  // @@protoc_insertion_point(field_release:mediapipe.RoiTrackingCalculatorOptions.landmarks_requirements)
  _has_bits_[0] &= ~0x00000004u;
  ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* temp = landmarks_requirements_;
  landmarks_requirements_ = nullptr;
  return temp;
}
inline ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* RoiTrackingCalculatorOptions::_internal_mutable_landmarks_requirements() {
  _has_bits_[0] |= 0x00000004u;
  if (landmarks_requirements_ == nullptr) {
    auto* p = CreateMaybeMessage<::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements>(GetArenaForAllocation());
    landmarks_requirements_ = p;
  }
  return landmarks_requirements_;
}
inline ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* RoiTrackingCalculatorOptions::mutable_landmarks_requirements() {
  ::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* _msg = _internal_mutable_landmarks_requirements();
  // @@protoc_insertion_point(field_mutable:mediapipe.RoiTrackingCalculatorOptions.landmarks_requirements)
  return _msg;
}
inline void RoiTrackingCalculatorOptions::set_allocated_landmarks_requirements(::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements* landmarks_requirements) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete landmarks_requirements_;
  }
  if (landmarks_requirements) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::mediapipe::RoiTrackingCalculatorOptions_LandmarksRequirements>::GetOwningArena(landmarks_requirements);
    if (message_arena != submessage_arena) {
      landmarks_requirements = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, landmarks_requirements, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  landmarks_requirements_ = landmarks_requirements;
  // @@protoc_insertion_point(field_set_allocated:mediapipe.RoiTrackingCalculatorOptions.landmarks_requirements)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mediapipe

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_mediapipe_2fmodules_2fholistic_5flandmark_2fcalculators_2froi_5ftracking_5fcalculator_2eproto
